package com.documentos.wms_beirario.utils

enum class EnumTipoTarefaSigla(val id: Int) {

    RECEBIMENTO(1),
    ARMAZENAGEM(3),
    SEPARAÇÃO(4),
    EXPEDICAO(5),
    INVENTÁRIO(6),
    ETIQUETAGEM(7),
    REESTOCAGEM(8),
    PICKING(9),
    MONTAGEM(10),
    DESMONTAGEM(11),
    RECEBIMENTODEPRODUÇÃO(12),
    NORMATIVA(13),
    MOVIMENTAÇÃO(14),
    REIMPRESSAO(15),
    AUDITORIA(16),
    QUALIDADE(17),
    RESERVADEPEDIDO(18),
    CONFERENCIADEEBARQUE(19),
    AUDITORIADEESTOQUE(20),
    CONTROLEDEQUALIDADE(21),
    CONSULTACÓDIGODEBARRAS(100),
    CONFIGURAÇÃO(101)


}
