package com.documentos.wms_beirario.utils

enum class EnumTipoTarefaSigla(val sigla: String) {

    RECEBIMENTO("REC"),
    ARMAZENAGEM("ARM"),
    SEPARAÇÃO("SEP"),
    EXPEDICAO("EXP"),
    INVENTÁRIO("INV"),
    ETIQUETAGEM("ETQ"),
    MONTAGEM("MON"),
    NORMATIVA("NOR"),
    DESMONTAGEM("DMO"),
    REESTOCAGEM("RST"),
    PICKING("PIC"),
    RECEBIMENTODEPRODUÇÃO("RPR"),
    CONSULTACÓDIGODEBARRAS("CCB"),
    MOVIMENTAÇÃO("MOV"),
    TESTEVELOCIDADE("SPEED"),
    CONFIGURAÇÃO("CONFIG"),
    AUDITORIA("AUD"),
    REIMPRESSAO("RIP"),
    RESERVADEPEDIDO("RES"),
    CONTROLEDEQUALIDADE("CQ"),
    QUALIDADE("QUA"),
    CONFERENCIADEEBARQUE("CFE")


}
